/*User PKL Pass PKL*/

create table KATEGORI_SPAREPART
(
   KODE_KATEGORI VARCHAR2(30) not null,
   NAMA_KATEGORI VARCHAR2(50) not null,
   UOM VARCHAR2(20),
   UOM_PACKAGING VARCHAR2(20),
   SUB_CLASS VARCHAR2(40),
   ITEM_CLASS VARCHAR2(40),
   QTY_PERPACK number,
   LEAD_TIME number,
   constraint PK_KATEGORI_SPAREPART primary key (KODE_KATEGORI)
);
create table SPAREPART
(
   KODE_SPAREPART VARCHAR2(30) not null,
   KODE_KATEGORI VARCHAR2(30),
   STATUS_SPAREPART VARCHAR2(30),
   ITEM_GRADE VARCHAR2(20),
   REMARK_SPAREPART VARCHAR2(999),
   constraint PK_SPAREPART primary key (KODE_SPAREPART)
);

alter table SPAREPART
   add constraint FK_SPAREPAR_REFERENCE_KATEGORI foreign key (KODE_KATEGORI)
      references KATEGORI_SPAREPART (KODE_KATEGORI);
create table PENGAMBILAN
(
   KODE_PENGAMBILAN VARCHAR2(30) not null,
   KODE_SPAREPART VARCHAR2(30) not null,
   KODE_KATEGORI VARCHAR2(30) not null,
   DATE_PENGAMBILAN varchar2(30),
   STATUS_SPAREPARTP VARCHAR2(30),
   REMARK_PENGAMBILAN varchar2(999),
   constraint PK_PENGAMBILAN primary key (KODE_PENGAMBILAN, KODE_SPAREPART)
);

alter table PENGAMBILAN
   add constraint FK_PENGAMBI_REFERENCE_SPAREPAR foreign key (KODE_SPAREPART)
      references SPAREPART (KODE_SPAREPART);

alter table PENGAMBILAN
   add constraint FK_PENGAMBI_REFERENCE_KATEGORI foreign key (KODE_KATEGORI)
      references KATEGORI_SPAREPART (KODE_KATEGORI);
create table SUPPLIER
(
   KODE_SUPPLIER VARCHAR2(30) not null,
   NAMA_SUPPLIER VARCHAR2(100) not null,
   CONTACT_PERSON VARCHAR2(50),
   ALAMAT VARCHAR2(100),
   KOTA VARCHAR2(30),
   KODE_POS VARCHAR2(10),
   TELEPON_SUPPLIER VARCHAR2(15),
   FAX VARCHAR2(15),
   TIPE_SUPPLIER VARCHAR2(40),
   PRODUK_GRUP VARCHAR2(40),
   DEFAULT_CURRENCY VARCHAR2(20),
   ACCOUNT_AP VARCHAR2(100),
   STATUS_SUPPLIER VARCHAR2(20),
   REMARK_SUPPLIER VARCHAR2(999),
   NPWP VARCHAR2(50) not null,
   NAMA_NPWP VARCHAR2(50),
   ALAMAT_NPWP VARCHAR2(100),
   PAJAK_NPWP VARCHAR2(30),
   EMAIL_KONTAK VARCHAR2(50) not null,
   NAMA_KONTAK VARCHAR2(50),
   DIVISI_KONTAK VARCHAR2(50),
   TELEPON_KONTAK VARCHAR2(20),
   DESC_AP VARCHAR2(100) not null,
   DETAIL_AP VARCHAR2(999),
   constraint PK_SUPPLIER primary key (KODE_SUPPLIER, NPWP, EMAIL_KONTAK, DESC_AP)
);
create table T_PR
(
   KODE_TRANSAKSIPR VARCHAR2(40) not null,
   KODE_KATEGORI VARCHAR2(30) not null,
   DATE_PR VARCHAR2(30),
   PERMINTAAN_PENGIRIMAN VARCHAR2(30),
   PR_TYPE VARCHAR2(30),
   SUB_PR_TYPE VARCHAR2(30),
   REQ_DEPART VARCHAR2(30),
   QTY1 NUMBER,
   QTY2 NUMBER,
   DESKRIPSI_PR VARCHAR2(999),
   REMARK_PR VARCHAR2(999),
   STATUS_PR VARCHAR2(30),
   constraint PK_T_PR primary key (KODE_TRANSAKSIPR, KODE_KATEGORI)
);

alter table T_PR
   add constraint FK_T_PR_REFERENCE_KATEGORI foreign key (KODE_KATEGORI)
      references KATEGORI_SPAREPART (KODE_KATEGORI);
create table T_PO
(
   KODE_TRANSAKSIPO VARCHAR2(40) not null,
   KODE_TRANSAKSIPR VARCHAR2(40) not null,
   KODE_KATEGORI VARCHAR2(30) not null,
   KODE_SUPPLIER VARCHAR2(30) not null,
   NPWP VARCHAR2(50),
   EMAIL_KONTAK VARCHAR2(50),
   DESC_AP VARCHAR2(100),
   DATE_PO VARCHAR2(30),
   ENTITY_PO VARCHAR2(30),
   PO_TYPE VARCHAR2(40),
   UP VARCHAR2(50),
   TERM VARCHAR2(30),
   CURRENCY VARCHAR2(20),
   TAX_SCHEME VARCHAR2(20),
   PPN number,
   TOTAL_BARANG number,
   TOTAL_SELURUH number,
   DISCOUNT number,
   SHIPPING_ADDRESS VARCHAR2(200),
   REMARK_PO VARCHAR2(999),
   STATUS_PO VARCHAR2(30),
   constraint PK_T_PO primary key (KODE_TRANSAKSIPO, KODE_TRANSAKSIPR, KODE_KATEGORI, KODE_SUPPLIER)
);
alter table T_PO
   add constraint FK_T_PO_REFERENCE_T_PR foreign key (KODE_TRANSAKSIPR, KODE_KATEGORI)
      references T_PR (KODE_TRANSAKSIPR, KODE_KATEGORI);

alter table T_PO
   add constraint FK_T_PO_REFERENCE_SUPPLIER foreign key (KODE_SUPPLIER, NPWP, EMAIL_KONTAK, DESC_AP)
      references SUPPLIER (KODE_SUPPLIER, NPWP, EMAIL_KONTAK, DESC_AP);
create table PENERIMAAN
(
   KODE_PENERIMAAN VARCHAR2(40) not null,
   KODE_TRANSAKSIPO VARCHAR2(40) not null,
   KODE_SUPPLIER VARCHAR2(30) not null,
   KODE_KATEGORI VARCHAR2(30) not null,
   KODE_TRANSAKSIPR VARCHAR2(40),
   DATE_PENERIMAAN VARCHAR2(30),
   DN_VENDOR VARCHAR2(40),
   NO_POL VARCHAR2(20),
   GRN_QTY1 NUMBER,
   GRN_QTY2 NUMBER,
   OS_PO NUMBER,
   REMARK_PENERIMAAN VARCHAR2(999),
   constraint PK_PENERIMAAN primary key (KODE_PENERIMAAN, KODE_TRANSAKSIPO, KODE_SUPPLIER, KODE_KATEGORI)
);
alter table PENERIMAAN
   add constraint FK_PENERIMA_REFERENCE_T_PO foreign key (KODE_TRANSAKSIPO, KODE_TRANSAKSIPR, KODE_KATEGORI, KODE_SUPPLIER)
      references T_PO (KODE_TRANSAKSIPO, KODE_TRANSAKSIPR, KODE_KATEGORI, KODE_SUPPLIER);
create table TBBARU
(
   KODE_PENGAMBILAN VARCHAR2(30) not null,
   KODE_SPAREPART VARCHAR2(30) not null,
   TYPE_CODEB CLOB,
   ITEM_CODEB CLOB,
   ITEM_DESCB CLOB,
   constraint PK_TBBARU primary key (KODE_PENGAMBILAN, KODE_SPAREPART)
);

alter table TBBARU
   add constraint FK_TBBARU_REFERENCE_PENGAMBI foreign key (KODE_PENGAMBILAN, KODE_SPAREPART)
      references PENGAMBILAN (KODE_PENGAMBILAN, KODE_SPAREPART);
create table TBLAMA
(
   KODE_PENGAMBILAN VARCHAR2(30) not null,
   KODE_SPAREPART VARCHAR2(30) not null,
   TYPE_CODEL CLOB,
   ITEM_CODEL CLOB,
   ITEM_DESCL CLOB,
   constraint PK_TBLAMA primary key (KODE_PENGAMBILAN, KODE_SPAREPART)
);

alter table TBLAMA
   add constraint FK_TBLAMA_REFERENCE_PENGAMBI foreign key (KODE_PENGAMBILAN, KODE_SPAREPART)
      references PENGAMBILAN (KODE_PENGAMBILAN, KODE_SPAREPART);
